### ISSUE TITLE
Add an external jar dependency?

### ISSUE THREAD

**Issue by pollen5** [sdrausty/buildAPKs#11]
Hey there, i just discovered this yesterday and its nice but I'm stuck here, how would you add an external jar dependency in this case i want to use OkHttp

I downloaded okhttp.jar and its dependency okio.jar

What would i need to modify in buildOne.sh to link this jar files with it and use it.

Thanks.

**Comment by sdrausty** [comment]
https://github.com/sdrausty/buildAPKsArtifacts

**Comment by sdrausty** [comment]
@pollen5 thank you for sharing;  Canyou please send the code to this thread.

**Comment by sdrausty** [comment]
@pollen5 thank you for sharing;  Can you send the code to this thread?  Reference my previous post.

**Comment by sdrausty** [comment]
https://raw.githubusercontent.com/BuildAPKs/buildAPKs/master/scripts/build/build.one.bash

**Comment by SDRausty** [comment]
@pollen5 https://github.com/SDRausty/buildAPKs/issues/11

**Comment by SDRausty** [comment]
@pollen5 https://github.com/BuildAPKs/buildAPKs/issues/1

**Comment by SDRausty** [comment]
> Unifying native artifacts should be a simple solution.  File [bootclasspath.sh](https://github.com/shlibs/shlibs.sh/blob/master/bootclasspath.sh) is created to ease inegrating of native libraries that are present on device.

Reference from https://github.com/BuildAPKs/buildAPKs/issues/2#issuecomment-560134368
