### ISSUE TITLE
Problem with buildMyFirstAPK.sh

### ISSUE THREAD

**Issue by Archangel45** [sdrausty/buildAPKs#13]
```
File ./src/com/mobilepearls/flashlight/AboutActivity.java                                             ./src/com/mobilepearls/flashlight/FlashlightActivity.java                                             ./gen/com/mobilepearls/flashlight/R.java is missingFile ./gen/uk/co/jarofgreen/JustADamnCompass/R.java./src/uk/co/jarofgreen/JustADamnCompass/AboutActivity.java                                            ./src/uk/co/jarofgreen/JustADamnCompass/MainActivity.java is missing                                  find: ‘./Just-A-Damn-Compass/gen’: No such file or directory                                          File ./src/com/commonsware/android/appwidget/dice/AppWidget.java                                      ./src/com/commonsware/android/appwidget/dice/PairOfDiceActivity.java                                  ./gen/com/commonsware/android/appwidget/dice/R.java is missing                                        :
```

**Comment by sdrausty** [comment]
@Archangel45 you should be a little more specific.  What kind of problem do you have?
```
Calculating for /data/data/com.termux/files/home/buildAPKs...
  Results for /data/data/com.termux/files/home/buildAPKs.
  6 possible
  6 built
  2659 deposited in /storage/emulated/0/Download/builtAPKs/
  37 deposited in /storage/emulated/0/Download/builtAPKs/Entertainment20190202/
```

**Comment by sdrausty** [comment]
@Archangel45 can you be a little more specific please? What kind of problem do you have?
```
Calculating for /data/data/com.termux/files/home/buildAPKs...
  Results for /data/data/com.termux/files/home/buildAPKs.
  6 possible
  6 built
  2659 deposited in /storage/emulated/0/Download/builtAPKs/
  37 deposited in /storage/emulated/0/Download/builtAPKs/Entertainment20190202/

Releasing wake-lock: DONE
```

**Comment by sdrausty** [comment]
a) Can you share the error details?  
b) What is the result of `dpkg -s ecj`?

**Comment by sdrausty** [comment]
@Archangel45 see whether running [`fix.ecj.error.bash`](https://github.com/sdrausty/buildAPKs/blob/master/fix.ecj.error.bash) which installs a working version of `ecj` helps.  

You might also want to share your adventure https://github.com/termux/termux-packages/issues?q=is%3Aissue+ecj here too, especially https://github.com/termux/termux-packages/issues/3157 here.

**Comment by sdrausty** [comment]
This https://github.com/sdrausty/buildAPKs/commit/96c78ef7c20925c16ea2a20b546249690db67586 commit, and the accompanying series of commits automates resolving an ecj error.

**Comment by HemanthJabalpuri** [comment]
@sdrausty I also have this error.
I observed your build.one.bash and noticed that
`ecj -d ./obj -sourcepath . "$(find . -type f -name "*.java")"` takes java files as single arg.
So it may give File /path/to/som/javafile /path/to/some/javafile error and quit.
Removing the quotes may fix it. `ecj -d ./obj -sourcepath . $(find . -type f -name "*.java")`

I modified your build.one.bash for learning purpose and stipped it heavily. (Attached)
[build.txt](https://github.com/sdrausty/buildAPKs/files/3388392/build.txt)

**Comment by sdrausty** [comment]
@HemanthJabalpuri thank you for your contribution; I shall attempt to integrate your comments with `~/buildAPKs/scripts/build/build.github.bash HemanthJabalpuri` and similar

**Comment by sdrausty** [comment]
> I modified your build.one.bash for learning purpose and stripped it heavily

Wonderful distillation :flower_playing_cards:

**Comment by sdrausty** [comment]
> Removing the quotes may fix it. ecj -d ./obj -sourcepath . $(find . -type f -name "*.java")

resolved:
https://github.com/BuildAPKs/buildAPKs/commit/4a6ee78556eefeadf8b877205c58ce013e425a9f
https://github.com/sdrausty/buildAPKs/commit/730063a9caa09ac32d6778ec96caa1bbb97d6b37

Thank you 😁 ⛵🎆 🍯🕯️

**Comment by sdrausty** [comment]
If package `findutils` is installed `find ~/buildAPKs/sources/ -name "AndroidManifest.xml" -execdir ~/buildAPKs/scripts/sh/build/build.sh {} \;` will attempt to build everything available in subdirectors.  I hope you enjoy the addition to these projects.  Beautiful two in one that you created @HemanthJabalpuri, build one && build all 🎇

**Comment by HemanthJabalpuri** [comment]
> If package `findutils` is installed `find ~/buildAPKs/sources/ -name "AndroidManifest.xml" -execdir ~/buildAPKs/scripts/sh/build/build.sh {} \;` will attempt to build everything available in subdirectors. I hope you enjoy the addition to these projects. Beautiful two in one that you created @HemanthJabalpuri, build one && build all

May be below is just fine if we dont have findutils
```bash
for app $(find sources -name "AndroidManifest.xml"); do
    sh build.sh $(dirname $i);
done
```

Thanks for adding script to repo.

**Comment by sdrausty** [comment]
Managed to drop -execdir with:
```
for i in $(find sources/ -name "AndroidManifest.xml") ; do build.sh ${i%/*} ; done
```

find -exedir can be substituted with `xargs` too.  There shouldn't be a need for a loop  with xargs.

**Comment by sdrausty** [comment]
> Thanks for adding script to repo.

You are welcome;  My pleasure.
