### ISSUE TITLE
buildOne.bash --> Unbound "DAY" and "RDR"?

### ISSUE THREAD

**Issue by keiichiiownsu12** [sdrausty/buildAPKs#14]
Hi. I am attempting to compile a particular apk file (https://github.com/foolish314159/NHK-Easy-News), however when I run ./buildOne.bash, I get an error message stating:

./buildOne.bash: line 133: DAY: unbound variable
./buildOne.bash: line 48: RDR: unbound variable

I ran the script outside of the directory containing the android manifest file and received the same result.

**Comment by rafaelfbs** [comment]
Use the command "termux-setup-storage". [See the StackOverflow answer.](https://android.stackexchange.com/questions/166538/where-is-the-folder-that-termux-defaults-to/166541)

**Comment by Quasic** [comment]
It looks like DAY could be omitted, and RDR is the root directory?
RDR=$PREFIX
DAY=''

**Comment by keiichiiownsu12** [comment]
Well, I already had the termux storage directory set up.

I also used the build.dir (whichever one that was), and it seemed to run
fine (i.e. ran it in the directory with the android manifest xml file).
However, the script was returning an error: i.e. for every "asset" called
(i.e. menu bars, etc.), it was saying "could not find". (deleted the
scripts previously, but I can re-run it if you want the output.

So, that leads me to my second question: can your program build/compile any
random android app into an apk? (i.e. I was trying to build an app I
downloaded from github using your script). Or can it ONLY compile files
that are specifically compatible with it?

-Adam

**Comment by Quasic** [comment]
It doesn't build many projects. It is still a work in progress, I believe.

The unbound variables are usually ignored by bash. This would be ok for DAY, I think, but RDR is a path to a directory with scripts to fix issues and includes a var subdirectory for log files...I haven't used this script, but that's how I read it.

**Comment by HemanthJabalpuri** [comment]
Same here too...

**Comment by sdrausty** [comment]
Resolved: https://github.com/sdrausty/buildAPKs/commit/0b41b1e6796239dc32301854bff9b5063dfd7d07

**Comment by sdrausty** [comment]
buildOne.bash is currently [build.one.bash](https://raw.githubusercontent.com/BuildAPKs/buildAPKs/master/scripts/bash/build/build.one.bash)

**Comment by sdrausty** [comment]
`buildOne.bash` is currently [build.one.bash](https://raw.githubusercontent.com/BuildAPKs/buildAPKs/master/scripts/bash/build/build.one.bash).  New files [build.sh](https://raw.githubusercontent.com/BuildAPKs/buildAPKs/master/scripts/zsh/build/build.zsh) and [build.zsh](https://raw.githubusercontent.com/BuildAPKs/buildAPKs/master/scripts/zsh/build/build.zsh) are added for convenience.  Three shells are supported by [BuildAPKs](https://github.com/BuildAPKs): bash, sh and zsh.
