### ISSUE TITLE
Java is missing

### ISSUE THREAD

**Issue by hjyoung1** [sdrausty/buildAPKs#16]
I'm getting bunch of  missing errors when running setup.buildAPKs.bash
First time 
Followed this
https://sdrausty.github.io/docsBuildAPKs/easilyBuildAndroidAPKsOnDevice
![Screenshot_20190616-213411](https://user-images.githubusercontent.com/45882061/59566506-d8daae80-907e-11e9-9c3c-1514f43f2133.jpg)
Using Android Pie Oneplus 6

**Comment by sdrausty** [comment]
This is due to https://github.com/termux/termux-packages/issues?q=is%3Aissue+is%3Aopen+ecj ecj error.  Repost at https://github.com/termux/termux-packages/issues.

![Screenshot_20190616-122259](https://user-images.githubusercontent.com/27742457/59566714-b1112980-9031-11e9-9929-fdb40962ec9a.png)

In the meantime try fixing the error by running `fix.ecj.error.bash` and `fix.ecj4.6.error.bash` located in ~/buildAPKs/debs.

**Comment by hjyoung1** [comment]
![Screenshot_20190616-230355](https://user-images.githubusercontent.com/45882061/59567425-54425d00-908b-11e9-893b-b8040c71c4ec.jpg)

**Comment by sdrausty** [comment]
@hjyoung1 please confirm this resolution: https://github.com/sdrausty/buildAPKs/commit/fa0cfdae35fc3d363407a25a1d9ef1073597ff83

**Comment by sdrausty** [comment]
Use `git pull` to update.

**Comment by hjyoung1** [comment]
Works fine now. Thanks.

**Comment by sdrausty** [comment]
Thank you for confirming.  You still might want to repost at https://github.com/termux/termux-packages/issues?q=is%3Aissue+is%3Aopen+ecj to help other users, and this project, too.  Eclipse Java Compiler should be working from the main repository, and it has been broken for quite a while.

**Comment by sdrausty** [comment]
You're welcome and thank you for confirming.  You still might want to repost at https://github.com/termux/termux-packages/issues?q=is%3Aissue+is%3Aopen+ecj to help other users, and this project, too.  Eclipse Java Compiler should be working from the main repository, and it has been broken for quite a while.

**Comment by sdrausty** [comment]
You are welcome, and thanks for confirming;  This issue may want reposting at https://github.com/termux/termux-packages/issues?q=is%3Aissue+is%3Aopen+ecj to help other users, and this project, too. Eclipse Java Compiler should be working from the main repository, and it is broken for quite some time now.

**Comment by sdrausty** [comment]
You are welcome, and thanks for confirming;  This issue may want reposting at https://github.com/termux/termux-packages/issues?q=is%3Aissue+is%3Aopen+ecj to help other users, and this project too. Eclipse Java Compiler should be working correctly from the main repository, and it is broken for quite some time now.
