### ISSUE TITLE
Request to add support for gradle project

### ISSUE THREAD

**Issue by wyssdbd** [sdrausty/buildAPKs#17]
Error compiling gradle project

**Comment by sdrausty** [comment]
@wyssdbd are you familiar with https://github.com/sdrausty/buildAPKs/issues/11 Add an external jar dependency?

**Comment by sdrausty** [comment]
There are numerous ways to accomplish: 
> support for gradle project

Parsing a `build.gradle` file should resolve your request.  Should you make progress in automating this process, please share here your progress here @wyssdbd.

**Comment by sdrausty** [comment]
As far as automating parsing:  Artifacts should be loaded in $JDR, and simlinking them back into ~/buildAPKs/libs seems like the best option to conserve native space on device.  The ~/buildAPKs/sources directory can be a link to external storage to conserve native space on device.

**Comment by sdrausty** [comment]
As far as automating parsing:  Artifacts should be loaded in $JDR (possibly also unzipped into the `src` directory), and simlinked back into `~/buildAPKs/libs` seems like the best option to conserve native space on device.  The `~/buildAPKs/sources` directory can be a link to external storage to conserve native space.

**Comment by SDRausty** [comment]
Issue transferred to `Parsing Project Configuration Files` https://github.com/BuildAPKs/buildAPKs/issues/1

**Comment by SDRausty** [comment]
@wyssdbd I have transferred this issue to `Parsing Project Configuration Files` https://github.com/BuildAPKs/buildAPKs/issues/1

**Comment by SDRausty** [comment]
Any information that you care to share regarding this lofty goal is appreciated.

**Comment by SDRausty** [comment]
Reprint from Parsing Project Configuration Files https://github.com/BuildAPKs/buildAPKs/issues/1:

BuildAPKs could parse project configuration files automatically.  In order for buildAPKs to do so, it wants to know:
1. What are the configuration files:
   * `build.gradle`
   * `proguard-project.txt`

There are other configuration files that should be parsed.  What are the file names?


2. How to parse these files:
   * Should the libraries be downloaded and linked?
   * Should the libraries be downloaded and unpacked into the source?  This method may be more comfortable, and more transparent while working with the project sourcecode.


3. How should the build scripts integrate this simple task (parsing, downloading and linking).  Device space is important while working with multiple projects that want the same libraries.


Issue transferred from `Request to add support for gradle project` https://github.com/SDRausty/buildAPKs/issues/17

**Comment by SDRausty** [comment]
@wyssdbd https://github.com/BuildAPKs/buildAPKs/issues/1

**Comment by sudomain** [comment]
@SDRausty do you know of a guide that would help me parse a build.gradle file such as [this one](https://github.com/ankidroid/Anki-Android/blob/master/build.gradle) ? I currently build this app in Android Studio and Gradle's magic is a bit of a mystery to me.

**Comment by SDRausty** [comment]
> do you know of a guide 

@sudomain if you find one, please share https://github.com/BuildAPKs/buildAPKs/issues/2 here.
