### ISSUE TITLE
some more apps and questions

### ISSUE THREAD

**Issue by HemanthJabalpuri** [SDRausty/buildAPKs#18]
@SDRausty 

In this issue I will share some of extra apps that are compatible for building with buildAPKs.

**Comment by HemanthJabalpuri** [comment]
https://gitlab.com/f-droid-mirrors/hash_droid

**Comment by HemanthJabalpuri** [comment]
@SDRausty
can you please test above apps for compiling in android.

**Comment by SDRausty** [comment]
@HemanthJabalpuri thank you for the inspiration.  From https://github.com/SDRausty/buildAPKs/blob/master/conf/README.md
```
Should you find APKs that build with buildAPKs in the NUNAMES and NWNAMES files and elsewhere, please pull in ONAMES, UNAMES and the appropriate ma.bash file.  This means that two pull requests can be submitted!  One in buildAPKs, by adding a name to the corresponding ONAMES or UNAMES file.  And the second pull in the appropriate module repository, by adding an _AT_ line in the ma.bash file. 

1) To see the available ma.bash files you can use: find ~/buildAPKs/sources/ -type f -name ma.bash -exec cat {} \;

2) The line of interest in ma.bash is: find ~/buildAPKs/sources/ -type f -name ma.bash -exec cat {} \; | grep _AT_

	Usage: _AT_ org/repo commit
	Usage: _AT_ user/repo commit

Adding to ONAMES, UNAMES and the appropriate ma.bash file will enhance this progect.  To find the repository associated with a particular ma.bash file see ~/buildAPKs/.gitmodules

For the curious, the _AT_ function is located in: grep -r _AT_ ~/buildAPKs/scripts/bash/  

These files are located in ~/buildAPKs/conf/:

GAUTH		OATH token file

NUNAMES		Possible new APKs that may migrate to ONAMES, UNAMES and ma.bash.

NWNAMES		Possible new APKs that may migrate to ONAMES, UNAMES and ma.bash.

ONAMES		Organizations that build APKs with buildAPKs on device.

README.md	This file

TNAMES		Topics that build APKs with buildAPKs on device.

UNAMES		Users that build APKs with buildAPKs on device.

VERSIONID	buildAPKs version
<!-- README.md EOF -->
```

**Comment by HemanthJabalpuri** [comment]
@SDRausty
Thanks.

Any ideas for below things?
-External jar compiling
-External resources packing(from jar too)
-AIDL support
-Support Libraries support
-Kotlin

**Comment by SDRausty** [comment]
> Any ideas for below things?

Some of these topics are condensed here at this https://github.com/BuildAPKs/buildAPKs/issues/1 issue.  This https://github.com/BuildAPKs/buildAPKsTermuxApp repository was created when some of these subjects were being developed.   This issue https://github.com/BuildAPKs/buildAPKs/issues/1 is open for further enhancment of the questions you have asked here.

**Comment by SDRausty** [comment]
@HemanthJabalpuri if you can find the time, can you add some of the projects you have suggested following the outline in the [~/buildAPKs/conf/README.md](https://raw.githubusercontent.com/SDRausty/buildAPKs/master/conf/README.md) file.   Not all of the links from https://github.com/SDRausty/buildAPKs/issues/18#issuecomment-527429638_  have been parsed for a number of reasons, including development time with project scope and size in mind.  

As far as I can tell, there are quite a few more APK projects that can build beautifully with buildAPKs as is.  If you would also like to work on the other topics mentioned, please post https://github.com/BuildAPKs/buildAPKs/issues/1 at present.

**Comment by SDRausty** [comment]
As the ~/buildAPKs/conf/?NAMES files are new and are just being populated, contributing to [~/buildAPKs/conf/UNAMES](https://raw.githubusercontent.com/SDRausty/buildAPKs/master/conf/UNAMES) and [~/buildAPKs/conf/ONAMES](https://raw.githubusercontent.com/SDRausty/buildAPKs/master/conf/ONAMES) is no doubt the simplest way to enhance this project at present.  File ~/buildAPKs/conf/NUNAMES has 651 names awaiting sorting.  
   * https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request
   * https://github.com/SDRausty/buildAPKs/blob/master/conf/README.md

**Comment by SDRausty** [comment]
> can you please test above apps for compiling

@HemanthJabalpuri this commit https://github.com/SDRausty/buildAPKs/commit/619d9ed3eac34cbcfcfacb4114c30d01ea9a1a7a expands on https://github.com/SDRausty/buildAPKs/blob/master/var/conf/README.md 
`
This means that two very simple pull requests can be submitted:  One in buildAPKs, by adding a name to the corresponding CNAMES, ONAMES and UNAMES file, just one word in the corresponding file.  
`

**Comment by SDRausty** [comment]
This https://github.com/BuildAPKs/buildAPKs/commit/aa2fde90fb79c37a8c101bd1d7fc7b086bdaf68e commit, and accompanying commits in [shlibs.sh](https://github.com/shlibs/shlibs.bash/commits/master) and [shlibs.bash](https://github.com/shlibs/shlibs.sh/commits/master) create `B*NAMES` files in ~/buildAPKs/var/db with this workset: 
  * login 
  * download size 
  * build time
  *  number of AndroidManifest.xml files found 
  * number of APKs built

**Comment by SDRausty** [comment]
> can you please test above apps for compiling in android

@HemanthJabalpuri 
this repository https://github.com/BuildAPKs/db.BuildAPKs is created to assit in fullfilling your request.  This https://github.com/BuildAPKs/db.BuildAPKs/blob/master/BNAMES file holds statistics:  GitHub login, repository projects download size, build time, AndroidManifest.xml files found and built APKs found for each login that successfully built on device.

**Comment by SDRausty** [comment]
> Unifying native artifacts should be a simple solution.  File [bootclasspath.sh](https://github.com/shlibs/shlibs.sh/blob/master/bootclasspath.sh) is created to ease inegrating of native libraries that are present on device.

Reference from https://github.com/BuildAPKs/buildAPKs/issues/2#issuecomment-560134368

**Comment by Hydroper** [comment]
> @SDRausty
> Thanks.
> 
> Any ideas for below things?
> -External jar compiling
> -External resources packing(from jar too)
> -AIDL support
> -Support Libraries support
> -Kotlin

I was also wanting a language other than Java. I'm working in ShockScript and it's now finally time to generate code. It runs in Node.js already... I was wondering if someone is expert at generating DEX or CLASS and wants to integrate ShockScript with buildAPKs!

**Comment by SDRausty** [comment]
> to integrate:
External jar compiling
External resources packing(from jar too)
AIDL support
Support Libraries support
Kotlin
ShockScript with buildAPKs!

This Github team; [build-one-team](https://github.com/orgs/BuildAPKs/teams/build-one-team) is created on 20200105 to help resolve these requests.

**Comment by SDRausty** [comment]
Command `~/buildAPKs/build.repo.bash` was just added. It enables building just one repository. This command has been tested with https://github.com/search and https://gitlab.com/explore/ successfully.

EXAMPLE USAGE: build.repo.bash https://github.com/BuildAPKs/buildAPKs.entertainment

If you find more repo candidates for inclusion, please share an address to the sourcecode here in this topic.
