### ISSUE TITLE
BuildAPKs tots.bash EXIT: Signal 1 received by build.entertainment.bash!

### ISSUE THREAD

**Issue by xiaoshizuzhang** [SDRausty/buildAPKs#19]
$ ./buildAPKs/scripts/build/buildMyFirstAPK.sh 
Beginning buildAPKs setup:
\e[1;38;5;117mCommand `au` enables rollback; Available at https://wae.github.io/au/ : Continuing...
Unknown command: 'aapt' (run 'pkg help' for usage information)
fatal: destination path 'buildAPKs' already exists and is not an empty directory.
Cannot update ~/buildAPKs prerequisites: Continuing...

Already up to date.

Activating wake lock: DONE  

To always have wake lock set to on: `touch ~/buildAPKs/lock/set.lock`.

To update module ~/buildAPKs/sources/entertainment to the newest version remove the ~/buildAPKs/sources/entertainment/.git file and run build.entertainment.bash again. 

Beginning build in /data/data/com.termux/files/home/buildAPKs/sources/entertainment/PairOfDice
aapt: started...
aapt: done;  ecj: begun...
134 build.one.bash
Cleaning up...
Completed tasks in /data/data/com.termux/files/home/buildAPKs/sources/entertainment/PairOfDice

buildAPKs signal 160 received by build.one.bash in /data/data/com.termux/files/home/buildAPKs/sources/entertainment/PairOfDice by build.one.bash.  More information in `/data/data/com.termux/files/home/buildAPKs/log/stnderr.entertainment.log` file.

Running: tail -n 16 /data/data/com.termux/files/home/buildAPKs/log/stnderr.entertainment.log

Aborted
Cloning into '/data/data/com.termux/files/home/buildAPKs/debs/ecj4.6'...
dpkg: warning: ignoring request to remove ecj which isn't installed
Aborted
Aborted
Aborted
Aborted
Aborted
find: ‘/data/data/com.termux/files/home/buildAPKs/sources/entertainment/PairOfDice/bin’: No such file or directory
find: ‘/data/data/com.termux/files/home/buildAPKs/sources/entertainment/PairOfDice/gen’: No such file or directory
find: ‘/data/data/com.termux/files/home/buildAPKs/sources/entertainment/PairOfDice/obj’: No such file or directory
Aborted
Aborted
Aborted
Aborted
Aborted

Cleaning up...
Completed tasks in /data/data/com.termux/files/home/buildAPKs/sources/entertainment/PairOfDice

Beginning build in /data/data/com.termux/files/home/buildAPKs/sources/entertainment/Preview
aapt: started...
aapt: done;  ecj: begun...
134 build.one.bash
Cleaning up...
Completed tasks in /data/data/com.termux/files/home/buildAPKs/sources/entertainment/Preview

buildAPKs signal 160 received by build.one.bash in /data/data/com.termux/files/home/buildAPKs/sources/entertainment/Preview by build.one.bash.  More information in `/data/data/com.termux/files/home/buildAPKs/log/stnderr.entertainment.log` file.

Running: tail -n 16 /data/data/com.termux/files/home/buildAPKs/log/stnderr.entertainment.log

Cloning into '/data/data/com.termux/files/home/buildAPKs/debs/ecj4.6'...
dpkg: warning: ignoring request to remove ecj which isn't installed
Aborted
Aborted
Aborted
Aborted
Aborted
find: ‘/data/data/com.termux/files/home/buildAPKs/sources/entertainment/PairOfDice/bin’: No such file or directory
find: ‘/data/data/com.termux/files/home/buildAPKs/sources/entertainment/PairOfDice/gen’: No such file or directory
find: ‘/data/data/com.termux/files/home/buildAPKs/sources/entertainment/PairOfDice/obj’: No such file or directory
Aborted
Aborted
Aborted
Aborted
Aborted
Aborted

Cleaning up...
Completed tasks in /data/data/com.termux/files/home/buildAPKs/sources/entertainment/Preview

Beginning build in /data/data/com.termux/files/home/buildAPKs/sources/entertainment/ReadWrite
aapt: started...
aapt: done;  ecj: begun...
134 build.one.bash
Cleaning up...
Completed tasks in /data/data/com.termux/files/home/buildAPKs/sources/entertainment/ReadWrite

buildAPKs signal 160 received by build.one.bash in /data/data/com.termux/files/home/buildAPKs/sources/entertainment/ReadWrite by build.one.bash.  More information in `/data/data/com.termux/files/home/buildAPKs/log/stnderr.entertainment.log` file.

Running: tail -n 16 /data/data/com.termux/files/home/buildAPKs/log/stnderr.entertainment.log

dpkg: warning: ignoring request to remove ecj which isn't installed
Aborted
Aborted
Aborted
Aborted
Aborted
find: ‘/data/data/com.termux/files/home/buildAPKs/sources/entertainment/PairOfDice/bin’: No such file or directory
find: ‘/data/data/com.termux/files/home/buildAPKs/sources/entertainment/PairOfDice/gen’: No such file or directory
find: ‘/data/data/com.termux/files/home/buildAPKs/sources/entertainment/PairOfDice/obj’: No such file or directory
Aborted
Aborted
Aborted
Aborted
Aborted
Aborted
Aborted

Cleaning up...
Completed tasks in /data/data/com.termux/files/home/buildAPKs/sources/entertainment/ReadWrite

Beginning build in /data/data/com.termux/files/home/buildAPKs/sources/entertainment/com.mobilepearls.flashlight
aapt: started...
aapt: done;  ecj: begun...
134 build.one.bash
Cleaning up...
Completed tasks in /data/data/com.termux/files/home/buildAPKs/sources/entertainment/com.mobilepearls.flashlight

buildAPKs signal 160 received by build.one.bash in /data/data/com.termux/files/home/buildAPKs/sources/entertainment/com.mobilepearls.flashlight by build.one.bash.  More information in `/data/data/com.termux/files/home/buildAPKs/log/stnderr.entertainment.log` file.

Running: tail -n 16 /data/data/com.termux/files/home/buildAPKs/log/stnderr.entertainment.log

Aborted
Aborted
Aborted
Aborted
Aborted
find: ‘/data/data/com.termux/files/home/buildAPKs/sources/entertainment/PairOfDice/bin’: No such file or directory
find: ‘/data/data/com.termux/files/home/buildAPKs/sources/entertainment/PairOfDice/gen’: No such file or directory
find: ‘/data/data/com.termux/files/home/buildAPKs/sources/entertainment/PairOfDice/obj’: No such file or directory
Aborted
Aborted
Aborted
Aborted
Aborted
Aborted
Aborted
Aborted

Cleaning up...
Completed tasks in /data/data/com.termux/files/home/buildAPKs/sources/entertainment/com.mobilepearls.flashlight

Beginning build in /data/data/com.termux/files/home/buildAPKs/sources/entertainment/uk.co.jarofgreen.JustADamnCompass
aapt: started...
aapt: done;  ecj: begun...
134 build.one.bash
Cleaning up...
Completed tasks in /data/data/com.termux/files/home/buildAPKs/sources/entertainment/uk.co.jarofgreen.JustADamnCompass

buildAPKs signal 160 received by build.one.bash in /data/data/com.termux/files/home/buildAPKs/sources/entertainment/uk.co.jarofgreen.JustADamnCompass by build.one.bash.  More information in `/data/data/com.termux/files/home/buildAPKs/log/stnderr.entertainment.log` file.

Running: tail -n 16 /data/data/com.termux/files/home/buildAPKs/log/stnderr.entertainment.log

Aborted
Aborted
Aborted
Aborted
find: ‘/data/data/com.termux/files/home/buildAPKs/sources/entertainment/PairOfDice/bin’: No such file or directory
find: ‘/data/data/com.termux/files/home/buildAPKs/sources/entertainment/PairOfDice/gen’: No such file or directory
find: ‘/data/data/com.termux/files/home/buildAPKs/sources/entertainment/PairOfDice/obj’: No such file or directory
Aborted
Aborted
Aborted
Aborted
Aborted
Aborted
Aborted
Aborted
Aborted

Cleaning up...
Completed tasks in /data/data/com.termux/files/home/buildAPKs/sources/entertainment/uk.co.jarofgreen.JustADamnCompass

Calculating for ~/buildAPKs/.  This may take a while;  Please be patient.

The total increases as modules are added;  The build scripts add modules and create APKs on device.  Results for ~/buildAPKs/sources/:

  5 possible.total
  0 built.total

Results for ~/buildAPKs/sources/entertainment/:

  5 possible
  0 built
ls: cannot access '/data/data/com.termux/files/home/buildAPKs/cache/builtAPKs/entertainment20190923': No such file or directory
/data/data/com.termux/files/home/buildAPKs/scripts/bash/shlibs/tots.bash: line 60: 0

Releasing wake lock: DONE  

To always have wake lock set to on: `touch ~/buildAPKs/lock/set.lock`.

BuildAPKs tots.bash ERROR:  Generated script error 2 near or at line number 60 by `wc`! - 1 : syntax error: invalid arithmetic operator (error token is "Releasing wake lock: DONE  

To always have wake lock set to on: `touch ~/buildAPKs/lock/set.lock`.

BuildAPKs tots.bash ERROR:  Generated script error 2 near or at line number 60 by `wc`! - 1 ")

Build APKs (Android Package Kits) with scripts in ~/buildAPKs/scripts/bash/build/:

build.apps.bash
build.clocks.bash
build.compasses.bash
build.developers.tools.bash
build.dir.bash
build.entertainment.bash
build.games.bash
build.github.orgs.bash
build.github.topics.bash
build.github.users.bash
build.live.wallpapers.bash
build.one.bash
build.samples.bash
buildAll.bash
buildApplications.bash
buildBrowsers.bash
buildFlashlights.bash
buildGames.bash
buildSamples.bash
buildTop10.bash
buildTutorials.bash
buildWidgets.bash

Releasing wake lock: rm: cannot remove '/data/data/com.termux/files/home/buildAPKs/lock/wake.27104.lock': No such file or directory

Releasing wake lock: rm: cannot remove '/data/data/com.termux/files/home/buildAPKs/lock/wake.27104.lock': No such file or directory
BuildAPKs tots.bash EXIT: Signal 1 received by build.entertainment.bash!

**Comment by SDRausty** [comment]
@xiaoshizuzhang try restarting from scratch:
> fatal: destination path 'buildAPKs' already exists and is not an empty directory.

```
mv ~/buildAPKs ~/b0
~/b0/scripts/bash/init/setup.buildAPKs.bash
~/buildAPKs/scripts/bash/build/build.entertainment.bash
```

**Comment by SDRausty** [comment]
```
[07:44~]$ ~/buildAPKs/scripts/bash/build/build.entertainment.bash
Already up to date.

Activating wake lock: DONE

To always have wake lock set to on: `touch ~/buildAPKs/lock/set.lock`.

To update module ~/buildAPKs/sources/entertainment to the newest version remove the ~/buildAPKs/sources/entertainment/.git file and run build.entertainm
ent.bash again.

Beginning build in /data/data/com.termux/files/home/buildAPKs/sources/entertainment/ReadWrite
aapt: started...
aapt: done;  ecj: begun...
ecj: done;  dx: started...
dx: done;  Making com.commonsware.android.readwrite.apk...
Adding classes.dex to com.commonsware.android.readwrite.apk...
 'classes.dex'...
Signing com.commonsware.android.readwrite.apk...
Creating new keystore (using 'android' as password and 'alias' as the key alias).
Copied com.commonsware.android.readwrite.apk to Download/builtAPKs/entertainment20190923/com.commonsware.android.readwrite.1569239108.apk
The APK com.commonsware.android.readwrite.apk file can be installed from Download/builtAPKs/entertainment20190923/com.commonsware.android.readwrite.1569
239108.apk
Share https://wiki.termux.com/wiki/Development everwhere🌎🌍🌏🌐!
Cleaning up...
Completed tasks in /data/data/com.termux/files/home/buildAPKs/sources/entertainment/ReadWrite


Beginning build in /data/data/com.termux/files/home/buildAPKs/sources/entertainment/Preview
aapt: started...
aapt: done;  ecj: begun...
ecj: done;  dx: started...
dx: done;  Making com.commonsware.android.camera.apk...
Adding classes.dex to com.commonsware.android.camera.apk...
 'classes.dex'...
Signing com.commonsware.android.camera.apk...
Creating new keystore (using 'android' as password and 'alias' as the key alias).
Copied com.commonsware.android.camera.apk to Download/builtAPKs/entertainment20190923/com.commonsware.android.camera.1569239114.apk
The APK com.commonsware.android.camera.apk file can be installed from Download/builtAPKs/entertainment20190923/com.commonsware.android.camera.1569239114
.apk
Share https://wiki.termux.com/wiki/Development everwhere🌎🌍🌏🌐!
Cleaning up...
Completed tasks in /data/data/com.termux/files/home/buildAPKs/sources/entertainment/Preview


Beginning build in /data/data/com.termux/files/home/buildAPKs/sources/entertainment/PairOfDice
aapt: started...
aapt: done;  ecj: begun...
ecj: done;  dx: started...
dx: done;  Making com.commonsware.android.appwidget.dice.apk...
Adding classes.dex to com.commonsware.android.appwidget.dice.apk...
 'classes.dex'...
Signing com.commonsware.android.appwidget.dice.apk...
Creating new keystore (using 'android' as password and 'alias' as the key alias).
Copied com.commonsware.android.appwidget.dice.apk to Download/builtAPKs/entertainment20190923/com.commonsware.android.appwidget.dice.1569239120.apk
The APK com.commonsware.android.appwidget.dice.apk file can be installed from Download/builtAPKs/entertainment20190923/com.commonsware.android.appwidget
.dice.1569239120.apk
Share https://wiki.termux.com/wiki/Development everwhere🌎🌍🌏🌐!
Cleaning up...
Completed tasks in /data/data/com.termux/files/home/buildAPKs/sources/entertainment/PairOfDice


Beginning build in /data/data/com.termux/files/home/buildAPKs/sources/entertainment/uk.co.jarofgreen.JustADamnCompass
aapt: started...
aapt: done;  ecj: begun...
ecj: done;  dx: started...
dx: done;  Making uk.co.jarofgreen.JustADamnCompass.apk...
Adding classes.dex to uk.co.jarofgreen.JustADamnCompass.apk...
 'classes.dex'...
Signing uk.co.jarofgreen.JustADamnCompass.apk...
Creating new keystore (using 'android' as password and 'alias' as the key alias).
Copied uk.co.jarofgreen.JustADamnCompass.apk to Download/builtAPKs/entertainment20190923/uk.co.jarofgreen.JustADamnCompass.1569239126.apk
The APK uk.co.jarofgreen.JustADamnCompass.apk file can be installed from Download/builtAPKs/entertainment20190923/uk.co.jarofgreen.JustADamnCompass.1569
239126.apk
Share https://wiki.termux.com/wiki/Development everwhere🌎🌍🌏🌐!
Cleaning up...
Completed tasks in /data/data/com.termux/files/home/buildAPKs/sources/entertainment/uk.co.jarofgreen.JustADamnCompass


Beginning build in /data/data/com.termux/files/home/buildAPKs/sources/entertainment/com.mobilepearls.flashlight
aapt: started...
aapt: done;  ecj: begun...
ecj: done;  dx: started...
dx: done;  Making com.mobilepearls.flashlight.apk...
Adding classes.dex to com.mobilepearls.flashlight.apk...
 'classes.dex'...
Signing com.mobilepearls.flashlight.apk...
Creating new keystore (using 'android' as password and 'alias' as the key alias).
Copied com.mobilepearls.flashlight.apk to Download/builtAPKs/entertainment20190923/com.mobilepearls.flashlight.1569239132.apk
The APK com.mobilepearls.flashlight.apk file can be installed from Download/builtAPKs/entertainment20190923/com.mobilepearls.flashlight.1569239132.apk
Share https://wiki.termux.com/wiki/Development everwhere🌎🌍🌏🌐!
Cleaning up...
Completed tasks in /data/data/com.termux/files/home/buildAPKs/sources/entertainment/com.mobilepearls.flashlight

Calculating for ~/buildAPKs/.  This may take a while;  Please be patient.

The total increases as modules are added;  The build scripts add modules and create APKs on device.  Results for ~/buildAPKs/sources/:

   5 possible.total
   5 built.total

Results for ~/buildAPKs/sources/entertainment/:

   5 possible
   5 built

Results for Download/builtAPKs/:

        9935 deposited in Download/builtAPKs/
        10 deposited in Download/builtAPKs/entertainment20190923/

Build APKs (Android Package Kits) with scripts in ~/buildAPKs/scripts/bash/build/:

build.apps.bash
build.clocks.bash
build.compasses.bash
build.developers.tools.bash
build.dir.bash
build.entertainment.bash
build.games.bash
build.github.orgs.bash
build.github.topics.bash
build.github.users.bash
build.live.wallpapers.bash
build.one.bash
build.samples.bash
buildAll.bash
buildApplications.bash
buildBrowsers.bash
buildFlashlights.bash
buildGames.bash
buildSamples.bash
buildTop10.bash
buildTutorials.bash
buildWidgets.bash

Releasing wake lock: DONE

To always have wake lock set to on: `touch ~/buildAPKs/lock/set.lock`.

Build time: 36 seconds

[07:45~]$
```
