### ISSUE TITLE
Cannot change script permission on unrooted Nexus 6P

### ISSUE THREAD

**Issue by l00g33k** [sdrausty/buildAPKs#2]
Hello,

I am very glad to discover buildAPKs and am attempting to deploy it. I am very appriciative of the effort put into this project

I looked at the instructions in 'buildAPKs/docs/README.md':

    This project has bash scripts which help immensely in automating work. Make them executable by `chmod 750 script_name` if they are not already

However, it appears that this is not possible on my unrooted Nexus 6P. Is there any workaround? Would it be possible to move the scripts beneath '/data/data/com.termux/files' where chmod is possible? I would be happy to try but I'd love to hear about any wisdom before I jump:)

    $ ll
    total 24
    -rw-rw---- 1 root everybody 1907 Jun  6 17:27 build.sh
    -rw-rw---- 1 root everybody  325 Jun  6 17:27 buildAll.sh
    -rw-rw---- 1 root everybody  281 Jun  6 17:27 buildMyFirstAKPinTermux.sh
    -rw-rw---- 1 root everybody 1610 Jun  6 17:27 buildOne.sh
    -rw-rw---- 1 root everybody 2386 Jun  6 17:27 builda.sh
    -rw-rw---- 1 root everybody 1879 Jun  6 17:27 gclone
    terminal++@Nexus 6P:/sdcard/al/g/buildAPKs/scripts
    $ chmod 750 *
    chmod: changing permissions of 'build.sh': Operation not permitted
    chmod: changing permissions of 'buildAll.sh': Operation not permitted
    chmod: changing permissions of 'buildMyFirstAKPinTermux.sh': Operation not permitted
    chmod: changing permissions of 'buildOne.sh': Operation not permitted
    chmod: changing permissions of 'builda.sh': Operation not permitted
    chmod: changing permissions of 'gclone': Operation not permitted
    terminal++@Nexus 6P:/sdcard/al/g/buildAPKs/scripts

**Comment by sdrausty** [comment]
I'm sorry to hear that you didn't succeed on your first try. Thanks for posting your issue😀

What you ran into are different permissions in different parts of the filesystem in Android, i.e. 
/sdcard 
/storage 
/storage/external/Android/data/com.termux 
and 
/data/data/com.termux/files/home 
all have different permissions settings​.

Try again in your home directory, i.e. `cd` 
Then
```
apt update && apt upgrade
packages install aapt apksigner dx ecj git
git clone https://github.com/sdrausty/buildAPKs
./buildAPKs/buildMyFirstAKPinTermux.sh
```

Good luck😉

**Comment by l00g33k** [comment]
Hello,

Thank you for the quick response.

I see my problem. I put the repo on /sdcard/. I should have put it in termux's data partition. Hopefully this post will help some one else too.

Best.

**Comment by sdrausty** [comment]
I am glad you are making progress. 😊
