### ISSUE TITLE
error with buildMyFirstAPK.sh

### ISSUE THREAD

**Issue by ClzOn** [SDRausty/buildAPKs#20]
Script fails with 
`ls: cannot access '/data/data/com.termux/files/home/buildAPKs/var/cache/builtAPKs/entertainment.20191125': No such file or directory`
This happens because the actual folder is called `entertainment20191125`, without the dot between "entertainment" and the date.

**Comment by SDRausty** [comment]
@ClzOn please use `~/buildAPKs/update.buildAPKs.sh` to update, and post output. 
![Screenshot_20191125-182110_Termux](https://user-images.githubusercontent.com/27742457/69586431-919f0500-0fb0-11ea-9fea-5f8cefdc587a.jpg)

**Comment by ClzOn** [comment]
Still same issue after running the update script
![photo_2019-11-26 23 19 01](https://user-images.githubusercontent.com/54364653/69677408-2b46df00-10a3-11ea-90ad-5be76dc6b600.jpeg)
![photo_2019-11-26 23 16 46](https://user-images.githubusercontent.com/54364653/69677407-2aae4880-10a3-11ea-9c42-d7cc16ff8918.jpeg)

**Comment by SDRausty** [comment]
@ClzOn this commit https://github.com/SDRausty/buildAPKs/commit/a0ba8b2cdcf9bd8dfe5afadb930aaa3dc3f47627 should resolve `ls: cannot access`;  Use `~/buildAPKs/update.buildAPKs.sh` to update. 
 Thank you for sharing.

**Comment by SDRausty** [comment]
[Line 180 in file build.one.bash](https://github.com/SDRausty/buildAPKs/commit/a0ba8b2cdcf9bd8dfe5afadb930aaa3dc3f47627?diff=unified#diff-367dd2b0c4a0da684a8367aae2d95f0fL180) was triggering the signal.
