### ISSUE TITLE
Building 1 new APK

### ISSUE THREAD

**Issue by nomr72** [SDRausty/buildAPKs#21]
Hi,

I haven't found how to build just 1 APK, or how to add an APK.  How is this done?

I wanted to see if I could patch https://github.com/SubhamTyagi/Last-Launcher on my phone.

**Comment by SDRausty** [comment]
@nomr72 try ` ~/buildAPKs/build.github.bash https://github.com/SubhamTyagi/ `

**Comment by SDRausty** [comment]
```
Results for SubhamTyagi:
io.github.subhamtyagi.encryption.apk

Build time: 187 seconds
```

**Comment by nomr72** [comment]
It sounds like their encryption project builds, but Last-Launcher doesn't.  Is there a way to build just one project, so as to retry a lot and hunt down how to make it work?

**Comment by SDRausty** [comment]
> I wanted to see if I could patch
> Is there a way to build just one project

Here are a couple of methods to accomplish this;  Both use ` git clone `:
````
git clone https://github.com/SubhamTyagi/Last-Launcher
cd Last-Launcher
~/buildAPKs/build.github.bash 
```
Followed by this command:
```
~/buildAPKs/scripts/bash/build/build.in.dir.bash
```

` build.in.dir.bash ` finds AndroidManifest.xml files and initiates a build with ` build.one.bash `.  Another method is to use ` build.one.bash ` in the folder where the AndroidManifest.xml files are.  Alternatively, similar scripts can be found in the scripts/sh/build and  scripts/zsh/build directories.

**Comment by SDRausty** [comment]
> Is there a way to build just one project, so as to retry a lot and hunt down how to make it work?

Use ` tar ` to aid in iterating builds;  ` tar zcf Last-Launcher.tar.gz Last-Launcher ` will create a backup.  To untar, you can use ` tar xf Last-Launcher.tar.gz ` to recreate a pristeen copy of the Last-Launcher clone and retry making it work...

**Comment by nomr72** [comment]
Thanks sdrausty, those scripts were what I was looking for.  I usually use git to clean stuff up, doesn't need to rewrite unchanged files like tar does.

**Comment by SDRausty** [comment]
You are welcome @nomr72.  When you manage to build Last-Launcher please share here.

**Comment by SDRausty** [comment]
> I haven't found how to build just 1 APK, or how to add an APK. How is this done?

Command `~/buildAPKs/build.repo.bash` was just added. It enables building just one repository. This command has been tested with https://github.com/search and https://gitlab.com/explore/ successfully.

EXAMPLE USAGE: build.repo.bash https://github.com/BuildAPKs/buildAPKs.entertainment

If you find repo candidates for inclusion, please share an address to the sourcecode here in this topic.
