### ISSUE TITLE
Getting error when i am running zsh script (~/buildAPKs/scripts/bash/build/build.entertainment.bash)

### ISSUE THREAD

**Issue by srampv** [SDRausty/buildAPKs#24]
when I have run ~/buildAPKs/build.entertainment.bash got this error - [error1.log](https://github.com/SDRausty/buildAPKs/files/4200044/error1.log) -
when I have run ~/buildAPKs/scripts/bash/build/build.entertainment.bash got this error - [error.log](https://github.com/SDRausty/buildAPKs/files/4199989/error.log)

**Comment by SDRausty** [comment]
Ensure [Termux app](https://github.com/termux/termux-app) and [Termux packages](https://github.com/termux/termux-packages) are up to date.  This link https://github.com/WAE/au can help in keeping packages up to date with two keys + one tap.

**Comment by srampv** [comment]
I have run apt update , it seems everything up to date . 
![image](https://user-images.githubusercontent.com/6702943/74470884-eaba5e80-4e64-11ea-8e35-c8e5c9ad7b24.png)

**Comment by SDRausty** [comment]
As the error is in `ecj`, see whether https://github.com/BuildAPKs/debs.ecj4.6.buildAPKs this version of `ecj` helps.  Use `dpkg --purge ecj`, then `dpkg -install ecj4.6_4.6.2_all.deb` to downgrade `ecj` to this version.

There is another achived version of `ecj` here https://github.com/BuildAPKs/debs.ecj.buildAPKs too, if ecj4.6 doesn't work as anticipated.

**Comment by SDRausty** [comment]
> getting this error if I am not root user

@srampv compiling as root user may be the cause of the error:

http://tldp.org/guides.html and https://www.debian.org/doc/manuals/debian-handbook/index.en.html have more information
