### ISSUE TITLE
seems broken

### ISSUE THREAD

**Issue by commander-cb** [SDRausty/buildAPKs#28]
close -  fixed , i guess it was set to "gh" and not "http" as i expected
still had to mess around a bit, but have _all_ making now ...thx

$ ./buildMyFirstAPKs.sh
Already up to date.
Updating 4 additional components of ~/buildAPKs/:
Adding ~/buildAPKs/scripts/scripts/sh/shlibs...
Cloning into '/data/data/com.termux/files/home/buildAPKs/scripts/sh/shlibs'...
fatal: unable to connect to github.com:
github.com[0: 140.82.113.4]: errno=No route to host

fatal: clone of 'git://github.com/shlibs/shlibs.sh' into submodule path '/data/data/com.termux/files/home/buildAPKs/scripts/sh/shlibs' failed
Cannot add submodule ~/buildAPKs/scripts/scripts/sh/shlibs: Continuing...
Adding ~/buildAPKs/scripts/opt/db...
Cloning into '/data/data/com.termux/files/home/buildAPKs/opt/db'...
fatal: unable to connect to github.com:
github.com[0: 140.82.113.4]: errno=No route to host

fatal: clone of 'git://github.com/BuildAPKs/db.BuildAPKs' into submodule path '/data/data/com.termux/files/home/buildAPKs/opt/db' failed
Cannot add submodule ~/buildAPKs/scripts/opt/db: Continuing...
Adding ~/buildAPKs/scripts/scripts/bash/shlibs...
Cloning into '/data/data/com.termux/files/home/buildAPKs/scripts/bash/shlibs'...
fatal: unable to connect to github.com:
github.com[0: 140.82.113.4]: errno=No route to host

fatal: clone of 'git://github.com/shlibs/shlibs.bash' into submodule path '/data/data/com.termux/files/home/buildAPKs/scripts/bash/shlibs' failed
Cannot add submodule ~/buildAPKs/scripts/scripts/bash/shlibs: Continuing...
Adding ~/buildAPKs/scripts/opt/api/github...
Cloning into '/data/data/com.termux/files/home/buildAPKs/opt/api/github'...
fatal: unable to connect to github.com:
github.com[0: 140.82.113.4]: errno=No route to host

fatal: clone of 'git://github.com/BuildAPKs/buildAPKs.github' into submodule path '/data/data/com.termux/files/home/buildAPKs/opt/api/github' failed
Cannot add submodule ~/buildAPKs/scripts/opt/api/github: Continuing...
cp: cannot stat '/data/data/com.termux/files/home/buildAPKs/opt/db': No such file or directory

ERROR return value 1 received by buildMyFirstAPKs.sh ushlibs.bash buildMyFirstAPKs.sh trap.bash:  Exiting due to error signal -r near or at line number 13 by `cp` with return value 1.,.
Signal 139 exit received by buildMyFirstAPKs.sh ushlibs.bash trap.bash:  Exiting...

$ cd && git clone https://github.com/sdrausty/buildAPKs
Cloning into 'buildAPKs'...
remote: Enumerating objects: 197, done.
remote: Counting objects: 100% (197/197), done.
remote: Compressing objects: 100% (104/104), done.
remote: Total 5546 (delta 124), reused 144 (delta 73), pack-reused 5349
Receiving objects: 100% (5546/5546), 3.82 MiB | 2.57 MiB/s, done.
Resolving deltas: 100% (3384/3384), done.

**Comment by SDRausty** [comment]
> fatal: unable to connect to github.com:
github.com[0: 140.82.113.4]: errno=No route to host

Please check the wireless connection.

**Comment by SDRausty** [comment]
@commander-cb can you please explain msg:
> see edit -close

~ $ edit -close
No command edit found, did you mean:
 Command bvedit in package bvi
 Command dir in package coreutils
 Command dict in package dictd
 Command dig in package dnsutils
 Command ed in package ed
 Command git in package git
 Command dot in package graphviz
 Command hdir in package hfsutils
 Command mcedit in package mc
 Command mdir in package mtools
 Command dist in package nmh from the unstable-repo repository
 Command qgit in package qgit from the x11-repo repository
 Command redir in package redir
 Command evim in package vim-gtk from the x11-repo repository
 Command luit in package xorg-luit from the x11-repo reposito

**Comment by SDRausty** [comment]
> seems broken

> Please check the wireless connection.

What is your result?
