### ISSUE TITLE
lets try to build Pandroid projects

### ISSUE THREAD

**Issue by JanuszChmiel** [SDRausty/buildAPKs#29]
Pandroid is special Pascal language bundle available for Linux and Windows. The advanced programmer uses it to make special database application for his professional working. He has brought The possibility to code in Pascal programming language with no need to work with A separate .xml files to create GUI on The screen. I will upload A sample project, which will only create empty window. But it is A good Pandroid project template. My plan is very realistic. I would like to combine Bash script with special GTK based dialog system to create helper script which would combine yours apk builder with Pandroid.
The following experiment will begin on my flat now.
I will download Pandroid bundle for Linux not for Windows, since bitecode of SDK build tools is very probably different between SDK for Windows and Linux.
Issues are as follows.
Apache ant used to create .apk packages from Pandroid project do not support newer Java than version 7. It is known limitation of The Apache ant and can not be simply solved, because even core developers of Apache Ant do not try to solve this issue.
Unfortunately, it is very unlikely, that someone will obtain Openjdk 7.0 source and would try to make it so stable and reliable from Termux without Proot like todays Open jdk 11.0 is available. It seems to Me, that someone has made it very stable and that someone had to modify its source code.

So what about triing to replace Apache Ant by using APk builder script to build .dex and apk package?

Project is available here.
https://github.com/zeljkoc/Pandroid
git clone https://github.com/zeljkoc/pandroid.git
And I will upload shell script to build .apk as soon as possible. We need to find out how to replace Apache ant by routine used by MR Rausty build apk routines if it will be possible to achieve this goal.

I will be able to use standard Android text editors and I would build .apk by using build apk from Termux. 

I Am attaching build.sh and .xml files related to Apache Ant. Author has used Java version 1.6.
[build_debug_apk.sh.txt](https://github.com/SDRausty/buildAPKs/files/7402901/build_debug_apk.sh.txt)

Sure, remove .txt from The file extension. I need to bypass Github routines.
[build.xml.txt](https://github.com/SDRausty/buildAPKs/files/7402904/build.xml.txt)

All example projects can be found in The Examples folder. Project as Scrollview is ideal for testing.

**Comment by SDRausty** [comment]
>lets try to build Pandroid projects

This sounds fantastic @JanuszChmiel;  Please keep us updated of progress!
