### ISSUE TITLE
Artifacts only for API 23.x are supported.

### ISSUE THREAD

**Issue by yakovlevegor** [SDRausty/buildAPKs#30]
Could you please state in addition to `TSDKVERSION="23"` variable that the required versions of artifacts for appcompat, design, cardview and recyclerview should be 23.x only? Newer versions cause conflicts and don't work when linking a project.

**Comment by ghost** [comment]
In detail, there were resources conflicts between Android Jetpack components on aapt stage. This could be wrong because of android.jar version mismatch.
By the way, the F-Droid team had rewritten android sdkmanager util in python (https://gitlab.com/fdroid/sdkmanager), with which you can download any platform version on your device. Would there be any plans on integration?

**Comment by SDRausty** [comment]
> please state in addition to TSDKVERSION="23" variable that the required versions of artifacts for appcompat, design, cardview and recyclerview should be 23.x only?

@yakovlevegor thank you very much for sharing;  Can you supply a draft [pr](https://github.com/SDRausty/buildAPKs/pulls) with your suggestions similar to these commits please?

**Comment by SDRausty** [comment]
>supply a draft [pr](https://github.com/SDRausty/buildAPKs/pulls) 

Sometimes it is not possible to improve source code on the first attempt, drafts can be modified like the commit examples above.  I have a feeling that you probably would like to begin with file [`build.one.bash`](https://github.com/SDRausty/buildAPKs/blob/master/scripts/bash/build/build.one.bash).  The `build.one.bash` file  possibly should be divided and upgraded as it is quite big, and does not have very much versitality.

Used to build correctly until Termux updated `clang`:
`/data/data/com.termux/files/home/buildAPKs/sources/native2/san-angeles`

I not sure if you have noticed the depreciations, including with `clang`;  Have you?

**Comment by ghost** [comment]
> > supply a draft [pr](https://github.com/SDRausty/buildAPKs/pulls)
> 
> Sometimes it is not possible to improve source code on the first attempt, drafts can be modified like the commit examples above. I have a feeling that you probably would like to begin with file [`build.one.bash`](https://github.com/SDRausty/buildAPKs/blob/master/scripts/bash/build/build.one.bash). The `build.one.bash` file possibly should be divided and upgraded as it is quite big, and does not have very much versitality.
> 
> Used to build correctly until Termux updated `clang`: `/data/data/com.termux/files/home/buildAPKs/sources/native2/san-angeles`
> 
> I not sure if you have noticed the depreciations, including with `clang`; Have you?

No, haven't built san angeles in the past year. I'll see what's going on.

**Comment by SDRausty** [comment]
> I'll see what's going on.

The comman `build.native.bash` still builds both native apps, but `san angeles` no longer builds correctly.  Please confirm.

**Comment by ghost** [comment]
> > I'll see what's going on.
> 
> The comman `build.native.bash` still builds both native apps, but `san angeles` no longer builds correctly. Please confirm.

Yes, got this error:
`[ 25%] Building C object CMakeFiles/sanangeles.dir/app-android.c.o
Signal 42 generated in cmake && make build.one.bash doso.bash
Finished cmake and make in ~/buildAPKs/sources/native2/san-angeles/app/src/main/output/lib/arm64-v8a/.
No 'Android.mk' files were found: Continuing...
No 'jni' directory found: Continuing...
Signal generated native.bash build.one.bash build.one.bash: Continuing...
Adding classes.dex  to com.example.SanAngeles.1647952265.apk...
 'classes.dex'...
Signing com.example.SanAngeles.1647952265.apk: DONE`

Also got this issue with com.example.plasma

**Comment by SDRausty** [comment]
Can you please contribute upstream at https://github.com/termux/termux-packages/issues/9336 and similar [issue+clang](https://github.com/termux/termux-packages/issues?q=is%3Aissue+clang) regarding this serious new error with the updated `clang` Termux package as I cannot since my most recent ban there for [making things work on device](https://github.com/termux/proot/issues?q=is%3Aissue+SDRausty) instead of cracking/rooting Androids.

**Comment by ghost** [comment]
> Can you please contribute upstream at [termux/termux-packages#9336](https://github.com/termux/termux-packages/issues/9336) and similar [issue+clang](https://github.com/termux/termux-packages/issues?q=is%3Aissue+clang) regarding this serious new error with the updated `clang` Termux package as I cannot since my most recent ban there for [making things work on device](https://github.com/termux/proot/issues?q=is%3Aissue+SDRausty) instead of cracking/rooting Androids.

That's kinda odd, I've tried building it by hand, the error I'm getting with san angeles ties to OpenGL header missing:
`/data/data/com.termux/files/usr/include/GLES/glplatform.h:28:10: fatal error: 'KHR/khrplatform.h' file not found`

No error with plasma when building by hand.

**Comment by SDRausty** [comment]
I do not get errors with building plasma.
>building by hand.

Which commands did you use?  Does `build.sh` also produce an error?  What is the device architecture used?

**Comment by ghost** [comment]
> I do not get errors with building plasma.
> 
> > building by hand.
> 
> Which commands did you use? Does `build.sh` also produce an error? What is the device architecture used?

I just run `cmake -B build_dir && cmake --build build_dir` in cpp directory. My architecture's aarch64.

**Comment by ghost** [comment]
> I do not get errors with building plasma.
> 
> > building by hand.
> 
> Which commands did you use? Does `build.sh` also produce an error? What is the device architecture used?

Plasma compiles with the default script, but produces a different error:
`[100%] Linking C shared library libplasma.so
[100%] Built target plasma
Finished cmake and make in ~/buildAPKs/sources/native2/bitmap-plasma/app/src/main/output/lib/arm64-v8a/.
No 'Android.mk' files were found: Continuing...
No 'jni' directory found: Continuing...
Signal generated native.bash build.one.bash build.one.bash: Continuing...`

**Comment by SDRausty** [comment]
>run `cmake -B build_dir && cmake --build build_dir` in cpp directory. My architecture's aarch64

Thank you for sharing 🎼

**Comment by SDRausty** [comment]
https://github.com/agnostic-apollo/agnostic-apollo/issues/1
