### ISSUE TITLE
Trying to install a minimal helloworld app ask me for special permissions

### ISSUE THREAD

**Issue by AlbertoMata** [sdrausty/buildAPKs#4]
As far as I now, every permission that is needed should be declared in the Android Manifest. However, I have compiled a minimal project without any special feature (https://github.com/czak/minimal-android-project/) and still the installation manager ask me for access to the sdcard and calls info.  Does this binary add extra info to the app? pls help.

**Comment by sdrausty** [comment]
```
$ gcl https://github.com/czak/minimal-android-project/
Cloning into 'minimal-android-project'...
remote: Counting objects: 72, done.
remote: Total 72 (delta 0), reused 0 (delta 0), pack-reused 72
Unpacking objects: 100% (72/72), done.
$ cd minimal-android-project/
$ l
total 28
drwx------  4 u0_a93 u0_a93 4096 Sep  2 12:04 .
drwx------ 11 u0_a93 u0_a93 4096 Sep  2 12:04 ..
drwx------  7 u0_a93 u0_a93 4096 Sep  2 12:04 .git
-rw-------  1 u0_a93 u0_a93   14 Sep  2 12:04 .gitignore
-rw-------  1 u0_a93 u0_a93 1773 Sep  2 12:04 README.md
-rw-------  1 u0_a93 u0_a93  251 Sep  2 12:04 build.gradle
drwx------  3 u0_a93 u0_a93 4096 Sep  2 12:04 src
$ buildAll.sh
aapt begun
.
.
.
at com.android.dx.command.Main.main(Main.java:94)
1 error; aborting
```
How did you get https://github.com/czak/minimal-android-project/ to build on device in Termux @AlbertoMata ?

**Comment by AlbertoMata** [comment]
I just modified the buildOne.sh script. Since I don't have a sdcard, I remove the /sdcard/Download/ prefix and left the directory builtAPKs in the local enviroment. Also, I removed the "src" argument of the "find" comand, so the '*.java' files can be found without problems. It looks like this:

```
#!/data/data/com.termux/files/usr/bin/sh -e 
now=`date +%Y%m%d%s`
if [ ! -d "./bin" ]; then
mkdir ./bin
fi
if [ ! -d "./assets" ]; then
mkdir ./assets
fi
if [ ! -d "./res" ]; then
mkdir ./res
fi
if [ ! -d "builtAPKs" ]; then
mkdir builtAPKs
fi
echo "aapt begun"
aapt package -v -f \
             -M ./AndroidManifest.xml \
             -I $PREFIX/share/java/android.jar \
             -J src \
             -S res \
             -m

echo "ecj begun"
ecj -d ./obj -classpath $HOME/../usr/share/java/android.jar \
	     -sourcepath ./app/src $(find -type f -name "*.java")

echo "dx begun"
dx --dex --verbose --output=./bin/classes.dex ./obj

echo "Make the apk"

aapt package -v -f \
             -M ./AndroidManifest.xml \
             -S ./res \
	     -A ./assets \
             -F bin/step2.apk

echo "Add the classes.dex to the apk"
cd bin
aapt add -f step2.apk classes.dex

echo "Sign step2.apk"
apksigner ../step2-debug.key step2.apk ../step2.apk

cd ..
echo "And make it accessible to the outside world"
chmod 644 step2.apk

echo "Our Step2 app is ready to go"
cp step2.apk builtAPKs/step2$now.apk
echo "Copied to /sdcard/Download/builtAPKs/step2$now.apk"
echo "You can install step2$now.apk from /sdcard/Download/builtAPKs/"
sleep 1
```
**Before being executed, the buildOne.sh script should be placed in the same directory as the AndroidManifest.xml.** Run it; you'll end up with a mess of files and directories, but the apk file can be found in the ./builtAPKs directory (the build.gradle file is just ignored by the script.). Copy this apk file to your /storage/emulated/0/Download/ directory and tap on it. 

**The application works, but I don't know why request those permissions if they are not declared in the AndroidManifest.xml.** Thanks for the answers.

![capture _2017-09-02-14-27-41](https://user-images.githubusercontent.com/20963832/29998219-0be0ead8-8feb-11e7-8521-6bb30cbb3174.png)

![capture _2017-09-02-14-15-13](https://user-images.githubusercontent.com/20963832/29998220-14cc3e72-8feb-11e7-8c44-6cd3e4c69028.png)

**Comment by sdrausty** [comment]
@AlbertoMata It is really pleasing to see you building APKs in Termux on device.  I just checked `./scripts/build/buildHelloWorlds.sh` and noted that two of three of these APKs also ask for permissions, which as you well note are not necessary for a hello World app. 

![screenshot_20170902-212957](https://user-images.githubusercontent.com/27742457/29999876-ecebb33e-9025-11e7-93f9-97117508fb0c.png)

**Comment by AlbertoMata** [comment]
I found the answer in [StackOverflow](https://stackoverflow.com/questions/1747178/android-permissions-phone-calls-read-phone-state-and-identity). 

Those permissions (READ_PHONE_STATE and WRITE_EXTERNAL_STORAGE) are implicitly granted for applications that use a version of the API <= 3 (android 1.6). Also, if the attribute minSdkVersion is not specified is set by default to "1". Everything is oficially documented here:

https://developer.android.com/guide/topics/manifest/uses-sdk-element.html
https://developer.android.com/reference/android/Manifest.permission.html#WRITE_EXTERNAL_STORAGE
https://developer.android.com/reference/android/Manifest.permission.html#READ_PHONE_STATE

Adding the following line to the android manifest solves the problem (of course, you can set the attributes to any value that you require):

`<uses-sdk android:minSdkVersion="4" android:targetSdkVersion="4" />`

**I'm still curious, how the appt tool was ported to Termux?**

![capture _2017-09-03-15-29-42](https://user-images.githubusercontent.com/20963832/30006406-4f83e0ba-90bd-11e7-9ddd-f0540ca78980.png)

**Comment by sdrausty** [comment]
@AlbertoMata Thank you for your help regarding this issue.  This https://github.com/sdrausty/buildAPKsSamples/commit/bf5793dec174d5c69a8032cb9bf5e589052572e1 closes it.

**Comment by sdrausty** [comment]
@AlbertoMata it appears that setting it to SDK level 1 (one) is sufficient.  `aapt package -f \
	--min-sdk-version 1 \` https://github.com/sdrausty/buildAPKs/blob/master/scripts/build/buildOne.sh

Confirmations requested

**Comment by AlbertoMata** [comment]
I didn't know that argument even exists, although makes a lot of sense. Unfortunately, I don't have the enviroment configured in my cellphone this days, but I'm glad to see this project running up.
