### ISSUE TITLE
What are build times on a high end device compared to development machine?

### ISSUE THREAD

**Issue by wis** [sdrausty/buildAPKs#5]
nice project!
from this animation it looks like it took an hour.
how does it compare to a development machine? 
![](https://sdrausty.github.io/buildAPKs/bitpics/ps1.gif)

**Comment by sdrausty** [comment]
@wesamco thank you for contributing timing issue.  FAST.  Is my answer at present.

**Comment by sdrausty** [comment]
@wis [addNote.sh](https://raw.githubusercontent.com/sdrausty/buildAPKs/master/scripts/maintenance/addNote.sh) is added to buildAPKs to resolve this timing question.  It produces a timings file like [this one](https://sdrausty.github.io/buildAPKs/timings).  Please remember that doing anything on a smartphone and tablet will increase the compile time.  This includes running addNote.sh on the device to measure timing.

**Comment by sdrausty** [comment]
This issue is reopened; https://raw.githubusercontent.com/sdrausty/buildAPKs/master/scripts/maintenance/addNote.sh

motivation; timings is not complete at present

**Comment by Quasic** [comment]
I saw some actual numbers somewhere, but don't remember where.
Development machine is typically faster, because most devices are not designed for this, though in my experience, device can be faster for certain things. It largely depends on which machines are being compared.

**Comment by sdrausty** [comment]
Resolved: https://github.com/shlibs/shlibs/commit/82e5534a457ec46490e47cf0eccc1b1ac3a1e71b

**Comment by sdrausty** [comment]
![Screenshot_20190618-122149](https://user-images.githubusercontent.com/27742457/59701609-fc5b4180-91c3-11e9-9e20-41ee2eae2238.png)
