### ISSUE TITLE
Is it possible to run an Android project without creating apks and installing it?

### ISSUE THREAD

**Issue by thefzsalam** [sdrausty/buildAPKs#7]
It would really be a game changer if it is possible to run an android project like:
javac MyActivity.java
java com.myapp.MyActivty

without having to convert to dex and build apks.

It is possible theoretically, isn't it?

**Comment by finessin87** [comment]
You need the dependency list to be compiled where they are associated and depending on the complexity of the app (multiple classes, functions, etc...) would decide the amount of class folders are contained in the main code. Plus, the program lang. alone is not what the computer reads, it's the hash. Hope this helps.

**Comment by sdrausty** [comment]
Closed: beyond scope of project

**Comment by Quasic** [comment]
dalvikvm may currently be the most stable tool to run Java, though it needs to be in Dex format. Other VMs need more work, last I heard... memory leaks and things...
