### ISSUE TITLE
Something up with ecj 

### ISSUE THREAD

**Issue by SofeemLi** [sdrausty/buildAPKs#8]
I noticed that ecj doesn't behave like how it should. It seems like it always compiles against some hidden android.jar and doesn't allow more than one file/directory for the classpath. And whatever I put there doesn't get read anyway. I don't understand how anyone can even compile android code without including libraries or using thier own android.jar.

**Comment by sdrausty** [comment]
ECJ is being discussed here https://github.com/termux/termux-packages/issues/2717. Closing issue in favor of issue https://github.com/termux/termux-packages/issues/2717.

**Comment by sdrausty** [comment]
Old ecj debs have just been published here https://github.com/sdrausty/ecj2717 to assist Termux users that encounter *errors* with the current version.

Reference https://github.com/termux/termux-packages/issues/2717#issuecomment-412878096

**Comment by sdrausty** [comment]
If you encounter problems with ecj 4.7, use ecj 4.6.2
```
$ dpkg --purge ecj
```
```
$ au ecj4.6
```
https://sdrausty.github.io/au/

**Comment by sdrausty** [comment]
https://github.com/sdrausty/buildAPKs/tree/master/debs

**Comment by SDRausty** [comment]
https://github.com/BuildAPKs/debsBuildAPKs

**Comment by SDRausty** [comment]
@SofeemLi https://github.com/BuildAPKs/buildAPKs/issues/1

**Comment by SDRausty** [comment]
> understand how anyone can even compile android code without including libraries 

@SofeemLi https://github.com/BuildAPKs/buildAPKs/issues/1

**Comment by SDRausty** [comment]
>https://sdrausty.github.io/au/

https://wae.github.io/au/
