### ISSUE TITLE
errors with ecj

### ISSUE THREAD

**Issue by junaidahlone** [sdrausty/buildAPKs#9]
please tell why there are errors when i am compiling with ecj...

**Comment by sdrausty** [comment]
ECJ is being discussed here https://github.com/termux/termux-packages/issues/2717. Closing issue in favor of issue https://github.com/termux/termux-packages/issues/2717.

**Comment by sdrausty** [comment]
Old ecj debs have just been published here https://github.com/sdrausty/ecj2717 to assist Termux users that encounter *errors* with the current version.

Reference https://github.com/termux/termux-packages/issues/2717#issuecomment-412878096

**Comment by sdrausty** [comment]
If you encounter problems with ecj 4.7, use ecj 4.6.2
```
$ dpkg --purge ecj
```
```
$ au ecj4.6
```
https://sdrausty.github.io/au/

**Comment by sdrausty** [comment]
https://github.com/sdrausty/buildAPKs/tree/master/debs
